# -*- coding: utf-8 -*-
"""EL_t7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ5Y3NXZnrRJsUUCYqxjJu1gfOkOD-nt
"""

import sqlite3

conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

sample_data = [
    ("Laptop", 2, 50000),
    ("Laptop", 1, 50000),
    ("Phone", 3, 15000),
    ("Phone", 2, 15000),
    ("Tablet", 4, 20000),
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

conn.commit()
conn.close()

import pandas as pd
import matplotlib.pyplot as plt
import sqlite3

conn = sqlite3.connect("sales_data.db")
query = """
SELECT product,
       SUM(quantity) AS total_qty,
       SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)
print(df)

df.plot(kind="bar", x="product", y="revenue", legend=False)
plt.title("Revenue by Product")
plt.ylabel("Revenue")
plt.tight_layout()
plt.savefig("sales_chart.png")
plt.show()

#Query 2 - Top Selling Product by Revenue
query2 = """
SELECT product, SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
ORDER BY revenue DESC
LIMIT 1
"""
df2 = pd.read_sql_query(query2, conn)
print("Top Selling Product by Revenue:")
print(df2)